giscus:
  enable: true
  repo: small-lemon-qwq/small-lemon-qwq.github.io
  repo_id: R_kgDONhUWvg
  category: General
  category_id: DIC_kwDONhUWvs4DBPYq
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  theme: preferred_color_scheme
  lang: zh-CN
  input_position: bottom
  loading: lazy
math:
  every_page: true
  mathjax:
    enable: true
    tags: none
  katex:
    enable: false
    copy_tex: false