custom_file_path:
  style: source/_data/styles.css
giscus:
  enable: true
  repo: small-lemon-qwq/small-lemon-qwq.github.io
  repo_id: R_kgDONhUWvg
  category: General
  category_id: DIC_kwDONhUWvs4DBPYq
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  theme: preferred_color_scheme
  lang: zh-CN
  input_position: bottom
  loading: lazy
math:
  every_page: true
  mathjax:
    enable: true
    tags: none
  katex:
    enable: false
    copy_tex: false
excerpt_description: true
read_more_btn: true
reading_progress:
  enable: true
sidebar:
  display: hide
scheme: Gemini
social:
  GitHub: https://github.com/Cloudspots || fab fa-github
  Luogu: https://www.luogu.com.cn/user/760689 || icon-luogu
social_icons:
  enable: true
  icons_only: false
  transition: true
post_navigation: false
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
    style: default
  fold:
    enable: false
    height: 500
  language: true
back2top:
  enable: true
  sidebar: false
  scrollpercent: true
fancybox: true
mediumzoom: false
lazyload: false