giscus:
  enable: true
  repo: small-lemon-qwq/small-lemon-qwq.github.io
  repo_id: R_kgDONhUWvg
  category: General
  category_id: DIC_kwDONhUWvs4DBPYoq
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  theme: preferred_color_scheme
  lang: zh-CN
  input_position: bottom
  loading: lazy